var worldsConfig = [
	{
		"id":0,
		"name":"Overworld",
		"path":"worlds/overworld",
		"type":"default",
		"homes":"/homes.json",
		"warps":"/warps.json",
		"spawn":
			{
				"name":"Spawn",
				"x1":-298,
				"y1":673,
				"x2":702,
				"y2":-327,
				"color":"yellow",
				"opacity":0.15,
				"weight":1
			}
	},
	{
		"id":1,
		"name":"Nether",
		"path":"worlds/nether",
		"type":"other",
		"homes":"/homes.json",
		"warps":"",
		"spawn":
			{
				"name":"Hub",
				"x1":-44,
				"y1":-44,
				"x2":95,
				"y2":95,
				"color":"magenta",
				"opacity":0.15,
				"weight":1
			}
	},
	{
		"id":2,
		"name":"Overworld October 2020",
		"path":"worlds/overworldoct20",
		"type":"archive",
		"homes":"/homes.json",
		"warps":"/warps.json",
		"spawn":
			{
				"name":"Spawn",
				"x1":-298,
				"y1":673,
				"x2":702,
				"y2":-327,
				"color":"yellow",
				"opacity":0.15,
				"weight":1
			}
	}
];