var worldsConfig = [
	{
		"id":0,
		"name":"Overworld",
		"path":"worlds/overworld",
		"type":"default",
		"xsize":12000,
		"ysize":12000,
		"markers":[
			{
				"name":"Homes",
				"path":"/homes.json",
				"default":true
			},
			{
				"name":"Warps",
				"path":"/warps_raw.json",
				"raw":true,
				"default":false,
				"color":"yellow"
			}],
		"alter":{"Homes":["/time.json","/gone.json"]},
		"spawn":
			{
				"name":"Spawn",
				"x1":-298,
				"y1":673,
				"x2":702,
				"y2":-327,
				"color":"yellow",
				"opacity":0.15,
				"weight":1
			}
	},
	{
		"id":1,
		"name":"Nether",
		"path":"worlds/nether",
		"type":"other",
		"xsize":10000,
		"ysize":10000,
		"markers":[
			{
				"name":"Homes",
				"path":"/homes.json",
				"default":true
			}],
		"spawn":
			{
				"name":"Hub",
				"x1":-44,
				"y1":-44,
				"x2":95,
				"y2":95,
				"color":"magenta",
				"opacity":0.15,
				"weight":1
			}
	},
	{
		"id":2,
		"name":"Overworld October 2020",
		"path":"worlds/overworldoct20",
		"type":"archive",
		"xsize":12000,
		"ysize":12000,
		"markers":[
			{
				"name":"Homes",
				"path":"/homes.json",
				"default":true
			},
			{
				"name":"Warps",
				"path":"/warps.json",
				"default":false,
				"color":"yellow"
			}],
		"spawn":
			{
				"name":"Spawn",
				"x1":-298,
				"y1":673,
				"x2":702,
				"y2":-327,
				"color":"yellow",
				"opacity":0.15,
				"weight":1
			}
	}
];